import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { generateObject, NoObjectGeneratedError } from "ai";
import { z } from "zod";
import { PERSONA_COOKIE } from "@/lib/odoo/session";
import { agentModel } from "@/lib/agent/model";

/**
 * Follow-up chip suggestions, deliberately generated by a separate call
 * rather than a tool the main chat model decides whether to invoke. Tried
 * the tool-call approach first — asking the model to always call a
 * suggestFollowUps tool at the end of its turn — but a cheap model like
 * gpt-4o-mini skips it more often than not (confirmed live: it answered in
 * plain text and never called the tool). generateObject's structured
 * output is enforced by the provider, not by the model choosing to
 * cooperate, so this actually shows up every time instead of most times.
 */
export async function POST(req: Request) {
  const persona = (await cookies()).get(PERSONA_COOKIE)?.value;
  if (persona !== "admin" && persona !== "invoicing") {
    return NextResponse.json({ error: "Not permitted" }, { status: 403 });
  }

  const { userText, assistantText } = (await req.json()) as {
    userText?: string;
    assistantText?: string;
  };
  if (!assistantText) {
    return NextResponse.json({ suggestions: [] });
  }

  try {
    const { object } = await generateObject({
      model: agentModel,
      schema: z.object({
        suggestions: z
          .array(z.string().max(60))
          .min(2)
          .max(4)
          .describe("Short follow-up messages the user might naturally send next, in their own voice."),
      }),
      prompt: `An accounting assistant just replied to a user in a furniture business's admin tool.

The assistant can ONLY: find contacts/products; look up a sales/purchase order's or an
invoice/bill's status; run the Balance Sheet or Profit & Loss report; create a contact; create a
sales or purchase order; confirm a draft order; generate a customer invoice or vendor bill from a
confirmed order; register a payment against an invoice/bill via Bank or Cash. It cannot send
emails, print/export documents, or do anything outside that list.

User said: ${JSON.stringify(userText ?? "")}
Assistant replied: ${JSON.stringify(assistantText)}

Suggest 2-4 short follow-up messages this user might naturally send next — written as something
they'd actually type (e.g. "Confirm it", "Add 5 more Wooden Tables", "Show this month's P&L") —
using ONLY the capabilities above, ideally continuing the exact order/invoice just discussed. Under
8 words each. If the conversation has clearly ended (e.g. the user just said thanks) or nothing in
the capability list fits, return an empty array rather than inventing something off-list.`,
    });
    return NextResponse.json({ suggestions: object.suggestions });
  } catch (err) {
    if (NoObjectGeneratedError.isInstance(err)) {
      return NextResponse.json({ suggestions: [] });
    }
    throw err;
  }
}
